### PR TITLE
Implements write() for DESCRIPTION files backed by package archives

### PR DESCRIPTION
**Pull request by atheriel**
This PR implements `write()` functionality for `DESCRIPTION` files backed by package archives, which would be useful for a project of mine. I'm not totally sure why this was not implemented before, so forgive me if there is a principled reason to forbid it.

The approach is basically

* For zip archives, we can use the replace functionality in `zip()` to update the `DESCRIPTION` file in-place.

* For tar archives, we must (1) extract the package contents, (2) modify the `DESCRIPTION` file, and then (3) re-archive the result in the same fashion as `R CMD build`, since tar archives do not support in-place modification.

In addition, this PR updates the docs to remove the restriction and removes the test that an error would occur if a user tried to call the `write()` method.

Known issues:

* The tar archive may not preserve file order and does not preserve modification times on directory entries. I don't think either of these is a dealbreaker.

In addition, I have not tested this on Windows.

### CODE REVIEW

**Comment by atheriel** [comment]
Failing tests are the same ones as in master.

**Comment by gaborcsardi** [comment]
Unfortunately this is not so simple, because binary packages include `DESCRIPTION` information in some of the package metadata files as well, so if you only change the `DESCRIPTION` file in them, you create an inconsistent state.

**Comment by atheriel** [comment]
Ah, I didn't realize that. Do you think it's (a) possible to overcome this, say by splicing the new description into the metadata files, or (b) if it should only be offered for source packages?

**Comment by gaborcsardi** [comment]
It is possible to update the other files as well, of course. My main worry is that their format has changed over time, so we would need to do different things for packages that are for different R versions, potentially, after some research about the format. Also, it might change in the future, and if we don't keep track then we might create broken packages.

OTOH remotes is already doing this when it installs packages from various sources: https://github.com/r-lib/remotes/blob/b9b9aa043f30e090a471560c16707855c2a10bce/R/install-remote.R#L115 and pak/pkgdepends have similar code

**Comment by atheriel** [comment]
I'm happy to implement something equivalent to the code you linked to, it's more straightforward than I was expecting. However, I don't see the R-version-specific handling -- or is that just based on your other experiences?

**Comment by gaborcsardi** [comment]
> However, I don't see the R-version-specific handling

Yeah, that's what I remember. I could be wrong, or it might have been before R 3.2, and then we don't care too much.

**Comment by atheriel** [comment]
I've added functionality to update the `Meta/package.rds` files to keep them internally consistent. Take a look to see if the approach makes sense.

I've also kept it as a separate commit, but I'm happy to squash them if you prefer.

**Comment by gaborcsardi** [comment]
I am sorry for the long delay. I am not going to merge this, because I am slightly worried about the edge cases. For example `zip()` uses an external `zip` program, and that is not always available, and different `zip` versions work slightly differently across OSes. This is not easy to fix, unfortunately. 

The same is true for tar files, although the internal tar implementation helps there. Also, for tar files, it is somewhat wasteful to uncompress the file to read out `DESCRIPTION`, and then uncompress it again when you write it back.

Thanks for understanding!

**Comment by atheriel** [comment]
This is sad news (I have a project that would benefit from mutating package archives), but your concerns are understandable. Thanks for the time and consideration.

**Pull request closed without merging**
